# Generated by Django 5.1.2 on 2024-11-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField()),
                ('vote_scale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('VID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('vote_timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp.user')),
            ],
        ),
    ]
