# Generated by Django 5.1.2 on 2024-11-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='project',
            new_name='PID',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='user',
            new_name='UID',
        ),
    ]
